spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.vansoft.springcloud.entities # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件
emp:
  name: lisi
logging:
  level:
    com.vansoft.springcloud: debug
spring:
  profiles: dev
  application:
    name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个 name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8 # 数据库名称
    username: root
    password: root#123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
instance:
  instanceId: ${spring.application.name}:${server.port} 
  prefer-ip-address: true


---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.vansoft.springcloud.entities # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

logging:
  level:
    com.vansoft.springcloud: debug
spring:
  profiles: prod
  application:
    name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个 name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8 # 数据库名称
    username: root
    password: root#123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
    defaultZone: http://eureka6001.com:6001/eureka 
  instance:
  instanceId: ${spring.application.name}:${server.port}
  prefer-ip-address: true
emp:
  name: zhangsan
